package com.example.mobilecoursework

import androidx.compose.runtime.saveable.Saver
import androidx.compose.runtime.saveable.mapSaver

data class Flags (
    val flagName: String,
    val flagImage: Int
)

object FlagList {
    val flagNameList = listOf(
        Flags("Andorra", R.drawable.ad),
        Flags("United Arab Emirates", R.drawable.ae),
        Flags("Afghanistan", R.drawable.af),
//        Flags("Antigua and Barbuda", R.drawable.ag),
//        Flags("Anguilla", R.drawable.ai),
//        Flags("Albania", R.drawable.al),
//        Flags("Armenia", R.drawable.am),
//        Flags("American Samoa", R.drawable.`as`),
//        Flags("Angola", R.drawable.ao),
        Flags("Antarctica", R.drawable.aq),
        Flags("Argentina", R.drawable.ar),
        Flags("Austria", R.drawable.at),
        Flags("Australia", R.drawable.au),
//        Flags("Aruba", R.drawable.aw),
//        Flags("Aland Islands", R.drawable.ax),
        Flags("Azerbaijan", R.drawable.az),
//        Flags("Bosnia and Herzegovina", R.drawable.ba),
//        Flags("Barbados", R.drawable.bb),
        Flags("Bangladesh", R.drawable.bd),
        Flags("Belgium", R.drawable.be),
//        Flags("Burkina Faso", R.drawable.bf),
//        Flags("Bulgaria", R.drawable.bg),
//        Flags("Bahrain", R.drawable.bh),
//        Flags("Burundi", R.drawable.bi),
//        Flags("Benin", R.drawable.bj),
//        Flags("Saint-Barthélemy", R.drawable.bl),
//        Flags("Bermuda", R.drawable.bm),
//        Flags("Brunei Darussalam", R.drawable.bn),
//        Flags("Bolivia", R.drawable.bo),
        Flags("Netherlands", R.drawable.bq),
        Flags("Brazil", R.drawable.br),
//        Flags("Bahamas", R.drawable.bs),
//        Flags("Bhutan", R.drawable.bt),
//        Flags("Norway", R.drawable.bv),
//        Flags("Botswana", R.drawable.bw),
//        Flags("Belarus", R.drawable.by),
//        Flags("Belize", R.drawable.bz),
        Flags("Canada", R.drawable.ca),
//        Flags("Cocos_(Keeling)_Islands", R.drawable.cc),
//        Flags("Democratic_Republic_of_the_Congo", R.drawable.cd),
//        Flags("Central_African_Republic", R.drawable.cf),
//        Flags("Republic_of_the_Congo", R.drawable.cg),
//        Flags("Switzerland", R.drawable.ch),
//        Flags("Côte_d'Ivoire", R.drawable.ci),
//        Flags("Cook_Islands", R.drawable.ck),
//        Flags("Chile", R.drawable.cl),
//        Flags("Cameroon", R.drawable.cm),
//        Flags("People's_Republic_of_China", R.drawable.cn),
//        Flags("Colombia", R.drawable.co),
//        Flags("Costa Rica", R.drawable.cr),
//        Flags("Cuba", R.drawable.cu),
//        Flags("Cape Verde", R.drawable.cv),
//        Flags("Curaçao", R.drawable.cw),
//        Flags("Christmas Island", R.drawable.cx),
//        Flags("Cyprus", R.drawable.cy),
//        Flags("Czech Republic", R.drawable.cz),
        Flags("Germany", R.drawable.de),
//        Flags("Djibouti", R.drawable.dj),
//        Flags("Denmark", R.drawable.dk),
//        Flags("Dominica", R.drawable.dm),
//        Flags("Dominican Republic", R.drawable.dominic),
//        Flags("Algeria", R.drawable.dz),
//        Flags("Ecuador", R.drawable.ec),
//        Flags("Estonia", R.drawable.ee),
//        Flags("Egypt", R.drawable.eg),
//        Flags("Western Sahara", R.drawable.eh),
//        Flags("Eritrea", R.drawable.er),
//        Flags("Spain", R.drawable.es),
//        Flags("Ethiopia", R.drawable.et),
//        Flags("Europe", R.drawable.eu),
//        Flags("Finland", R.drawable.fi),
//        Flags("Fiji", R.drawable.fj),
//        Flags("Falkland Islands", R.drawable.fk),
//        Flags("Micronesia", R.drawable.fm),
//        Flags("Faroe Islands", R.drawable.fo),
//        Flags("French_Republic", R.drawable.fr),
//        Flags("Gabon", R.drawable.ga),
        Flags("United_Kingdom", R.drawable.gb),
        Flags("England", R.drawable.gbeng),
//        Flags("Northern Ireland", R.drawable.gbnir),
        Flags("Scotland", R.drawable.gbsct),
//        Flags("Wales", R.drawable.gbwls),
//        Flags("Grenada", R.drawable.gd),
//        Flags("Georgia", R.drawable.ge),
//        Flags("Guernsey", R.drawable.gg),
//        Flags("Ghana", R.drawable.gh),
//        Flags("Gibraltar", R.drawable.gi),
//        Flags("Greenland", R.drawable.gl),
//        Flags("Gambia", R.drawable.gm),
//        Flags("Guinea", R.drawable.gn),
//        Flags("Equatorial Guinea", R.drawable.gq),
//        Flags("Greece", R.drawable.gr),
//        Flags("South Georgia and the South Sandwich Islands", R.drawable.gs),
//        Flags("Guatemala", R.drawable.gt),
//        Flags("Guam", R.drawable.gu),
//        Flags("Guinea-Bissau", R.drawable.gw),
//        Flags("Guyana", R.drawable.gy),
//        Flags("Hong_Kong", R.drawable.hk),
//        Flags("Heard and Mcdonald Islands", R.drawable.hm),
//        Flags("Honduras", R.drawable.hn),
//        Flags("Croatia", R.drawable.hr),
//        Flags("Haiti", R.drawable.ht),
//        Flags("Hungary", R.drawable.hu),
//        Flags("Indonesia", R.drawable.id),
//        Flags("Ireland", R.drawable.ie),
//        Flags("Israel", R.drawable.il),
//        Flags("Isle_of_Mann", R.drawable.im),
        Flags("India", R.drawable.`in`),
//        Flags("Commissioner_of_the_British_Indian_Ocean_Territory", R.drawable.io),
        Flags("Iraq", R.drawable.iq),
        Flags("Iran", R.drawable.ir),
//        Flags("Iceland", R.drawable.lc),
        Flags("Italy", R.drawable.it),
//        Flags("Jersey", R.drawable.je),
        Flags("Jamaica", R.drawable.jm),
        Flags("Jordan", R.drawable.jo),
        Flags("Japan", R.drawable.jp),
//        Flags("Kenya", R.drawable.ke),
//        Flags("Kyrgyzstan", R.drawable.kg),
//        Flags("Cambodia", R.drawable.kh),
//        Flags("Kiribati", R.drawable.ki),
//        Flags("Comoros", R.drawable.km),
//        Flags("Saint Kitts and Nevis", R.drawable.kn),
        Flags("North Korea", R.drawable.kp),
        Flags("South Korea", R.drawable.kr),
//        Flags("Kuwait", R.drawable.kw),
//        Flags("Cayman_Islands", R.drawable.ky),
//        Flags("Kazakhstan", R.drawable.kz),
//        Flags("Laos", R.drawable.la),
//        Flags("Lebanon", R.drawable.lb),
//        Flags("Saint Lucia", R.drawable.lc),
//        Flags("Liechtenstein", R.drawable.li),
        Flags("Sri Lanka", R.drawable.lk),
//        Flags("Liberia", R.drawable.lr),
//        Flags("Lesotho", R.drawable.ls),
//        Flags("Lithuania", R.drawable.lt),
//        Flags("Luxembourg", R.drawable.lu),
//        Flags("Latvia", R.drawable.lv),
//        Flags("Libya", R.drawable.ly),
//        Flags("Morocco", R.drawable.ma),
//        Flags("Monaco", R.drawable.mc),
//        Flags("Moldova", R.drawable.md),
//        Flags("Montenegro", R.drawable.me),
//        Flags("French_Republic", R.drawable.mf),
//        Flags("Madagascar", R.drawable.mg),
//        Flags("Marshall_Islands", R.drawable.mh),
//        Flags("North_Macedonia", R.drawable.mk),
//        Flags("Mali", R.drawable.ml),
//        Flags("Myanmar", R.drawable.mm),
//        Flags("Mongolia", R.drawable.mn),
//        Flags("Macao", R.drawable.mo),
//        Flags("Northern_Mariana_Islands", R.drawable.mp),
//        Flags("French_Republic", R.drawable.mq),
//        Flags("Mauritania", R.drawable.mr),
//        Flags("Montserrat", R.drawable.ms),
//        Flags("Malta", R.drawable.mt),
//        Flags("Mauritius", R.drawable.mu),
        Flags("Maldives", R.drawable.mv),
//        Flags("Malawi", R.drawable.mw),
//        Flags("Mexico", R.drawable.mx),
//        Flags("Malaysia", R.drawable.my),
//        Flags("Mozambique", R.drawable.mz),
//        Flags("French_Republic", R.drawable.nc),
//        Flags("Niger", R.drawable.ne),
//        Flags("Norfolk Island", R.drawable.nf),
//        Flags("Nigeria", R.drawable.ng),
//        Flags("Nicaragua", R.drawable.ni),
        Flags("Netherlands", R.drawable.nl),
//        Flags("Norway", R.drawable.no),
        Flags("Nepal", R.drawable.np),
//        Flags("Nauru", R.drawable.nr),
//        Flags("Niue", R.drawable.nu),
        Flags("New Zealand", R.drawable.nz),
//        Flags("Oman", R.drawable.om),
//        Flags("Panama", R.drawable.pa),
//        Flags("Peru", R.drawable.pe),
//        Flags("French_Polynesia", R.drawable.pf),
//        Flags("Papua New Guinea", R.drawable.pg),
//        Flags("Philippines", R.drawable.ph),
        Flags("Pakistan", R.drawable.pk),
//        Flags("Poland", R.drawable.pl),
//        Flags("French_Republic", R.drawable.pm),
//        Flags("Pitcairn", R.drawable.pn),
//        Flags("Puerto_Rico", R.drawable.pr),
        Flags("Palestine", R.drawable.ps),
        Flags("Portugal", R.drawable.pt),
//        Flags("Palau", R.drawable.pw),
//        Flags("Paraguay", R.drawable.py),
        Flags("Qatar", R.drawable.qa),
//        Flags("French_Republic", R.drawable.re),
//        Flags("Romania", R.drawable.ro),
//        Flags("Serbia", R.drawable.rs),
        Flags("Russia", R.drawable.ru),
//        Flags("Rwanda", R.drawable.rw),
        Flags("Saudi_Arabia", R.drawable.sa),
//        Flags("Solomon_Islands", R.drawable.sb),
//        Flags("Seychelles", R.drawable.sc),
//        Flags("Sudan", R.drawable.sd),
//        Flags("Sweden", R.drawable.se),
        Flags("Singapore", R.drawable.sg),
//        Flags("Saint Helena", R.drawable.sh),
//        Flags("Slovenia", R.drawable.si),
//        Flags("Norway", R.drawable.sj),
//        Flags("Slovakia", R.drawable.sk),
//        Flags("Sierra_Leone", R.drawable.sl),
//        Flags("San_Marino", R.drawable.sm),
//        Flags("Senegal", R.drawable.sn),
//        Flags("Somalia", R.drawable.so),
//        Flags("Suriname", R.drawable.sr),
//        Flags("South_Sudan", R.drawable.ss),
//        Flags("Sao_Tome_and_Principe", R.drawable.st),
//        Flags("El_Salvador", R.drawable.sv),
//        Flags("Saint_Maarten", R.drawable.sx),
//        Flags("Syria", R.drawable.sy),
//        Flags("Eswatini", R.drawable.sz),
//        Flags("Turks_and_Caicos_Islands", R.drawable.tc),
//        Flags("Chad", R.drawable.td),
//        Flags("French_Southern_and_Antarctic_Lands", R.drawable.tf),
//        Flags("Togo", R.drawable.tg),
        Flags("Thailand", R.drawable.th),
//        Flags("Tajikistan", R.drawable.tj),
//        Flags("Tokelau", R.drawable.tk),
//        Flags("East_Timor", R.drawable.tl),
//        Flags("Turkmenistan", R.drawable.tm),
//        Flags("Tunisia", R.drawable.tn),
//        Flags("Tonga", R.drawable.to),
//        Flags("Turkey", R.drawable.tr),
//        Flags("Trinidad and Tobago", R.drawable.tt),
//        Flags("Tuvalu", R.drawable.tv),
//        Flags("Taiwan", R.drawable.tw),
//        Flags("Tanzania", R.drawable.tz),
//        Flags("Ukraine", R.drawable.ua),
//        Flags("Uganda", R.drawable.ug),
//        Flags("United_States", R.drawable.um),
//        Flags("United_States", R.drawable.us),
//        Flags("Uruguay", R.drawable.uy),
//        Flags("Uzbekistan", R.drawable.uz),
//        Flags("Vatican_City", R.drawable.va),
//        Flags("Saint_Vincent_and_the_Grenadines", R.drawable.vc),
//        Flags("Venezuela", R.drawable.ve),
//        Flags("British_Virgin_Islands", R.drawable.vg),
//        Flags("United_States_Virgin_Islands", R.drawable.vi),
//        Flags("Vietnam", R.drawable.vn),
//        Flags("Vanuatu", R.drawable.vu),
//        Flags("Wallis_and_Futuna", R.drawable.wf),
//        Flags("Samoa", R.drawable.ws),
//        Flags("Kosovo", R.drawable.xk),
//        Flags("Yemen", R.drawable.ye),
//        Flags("French_Republic", R.drawable.yt),
        Flags("South Africa", R.drawable.za),
//        Flags("Zambia", R.drawable.zm),
        Flags("Zimbabwe", R.drawable.zw)
    )
}